    p1 = User("张三","12345")
    p2 = User("1","1")
    Data.userList.append(p1)
    Data.userList.append(p2)
    b1= Book("三体","刘慈欣")
    b2=Book("三国演绎","罗贯中")
    Data.bookList.append(b1)
    Data.bookList.append(b2)
    a1 = Admin("0","0")
    Data.userList.append(a1)